- name: Create a jenkins job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', '/tmp/pipeline.xml') }}"
    name: "test"
    url: "http://172.31.13.40:8080"
    user: "admin"
    token: "11f73e73eb52befc32e4d0aed578a10633"
  loop:
    - { repoName: "cart", componentName: "cart" }
