- name: Create Pipeline Jobs
  community.general.jenkins_job:
    config: "{{ lookup('template', '/tmp/pipeline.xml') }}"
    name: "{{item.folderName}}{{item.jobName}}"
    url: "http://172.31.13.40:8080"
    user: "admin"
    token: "11f73e73eb52befc32e4d0aed578a10633"
  loop:
    - { jobName: "cart", folderName: "",  repoName: "cart", componentName: "cart" }
