folders:
  - {name: "CI-Pipelines", description: "CI Pipeline Jobs for All RoboShop Components"}

pipelineJobs:
  - { jobName: "cart", folderName: "CI-Pipelines/",  repoName: "cart", componentName: "cart" }
